---
name: credit_card_app
description: >
  A credit card mobile app that allows an administrator to capture 
  credit card details, complete some checks on it and then store it locally to 
  storage. It also allows capturing the details by scanning a credit card.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  # equatable: ^2.0.5
  # flow_builder: ^0.0.9
  flutter_credit_card: ^3.0.7
  get_it: ^7.6.4
  injectable: ^2.3.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

  # Scan Page
  camera: ^0.10.5+4
  image_picker: ^1.0.4
  permission_handler: ^11.0.0

  # Hive DB
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Countries
  dash_flags: ^0.1.1

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  
  # Hive DB
  hive_generator: ^2.0.1
  build_runner: ^2.4.6

  injectable_generator: ^2.4.0
  freezed: ^2.4.2
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/
