---
name: credit_card_app
description: >
  A credit card mobile app that allows an administrator to capture 
  credit card details, complete some checks on it and then store it locally to 
  storage. It also allows capturing the details by scanning a credit card.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  bloc: ^8.1.2
  camera: ^0.10.5+5
  cupertino_icons: ^1.0.6
  dash_flags: ^0.1.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_credit_card: ^4.0.1
  flutter_hooks: ^0.20.3
  freezed_annotation: ^2.4.1
  get_it: ^7.6.4
  google_fonts: ^6.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  image_picker: ^1.0.4
  injectable: ^2.3.2
  json_annotation: ^4.8.1
  path: ^1.8.3
  path_provider: ^2.1.1
  permission_handler: ^11.0.1

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.5
  hive_generator: ^2.0.1
  injectable_generator: ^2.4.1
  json_serializable: ^6.7.1
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/
