name: CI
on:
    push:
        branches:
            [main]
        paths-ignore: 
            - '**/README.md'

    pull_request:
        branches:
            [main]

    workflow_dispatch:

jobs:
    build:
        name: flutter build
        runs-on: ubuntu-latest
        env:
            JAVA_VERSION: "11.0"
            FLUTTER_VERSION: "3.13.x"
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-java@v3
              with:
                distribution: 'zulu'
                java-version: '17'
                cache: 'gradle'
            - uses: subosito/flutter-action@v2 
              with:
                flutter-version: $
                channel: 'stable'
                cache: true
            
            - run: flutter pub get
            - run: flutter analyze
            - run: flutter test

            