---
name: Lint Code Base

on:
  push:
    branches: 
      [main, master]
  pull_request:
    branches: 
      [main, master]

  workflow_dispatch:

    
jobs:
  build:
    name: Flutter Build
    runs-on: ubuntu-latest
    env: 
      FLUTTER_VERSION: "3.13.x"
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Flutter Actions
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.13.x
          # cache: true
      
      - run: flutter --version
      - run: flutter pub get
      - run: flutter analyze

          
  run-lint:
    name: Run Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with: 
          fetch-depth: 0
      
      - name: Setup Flutter SDK
        uses: flutter-actions/setup-flutter@v2
        with:
          channel: stable
          version: 3.13.x

      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.13.x
          # cache: true
      
      - run: flutter --version

      - name: Install dependencies
        run: flutter pub get

      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: true
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
